name: Test Local Self-Hosted Runner

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - name: Display System Info
              run: |
                  echo "OS: $(uname -s || ver)" # 
                  echo "Current User: $(whoami)" # gets the name of the current user
                  echo "Working Directory: $(pwd)" # gets the working directory

            - name: Run a simple test
              run: |
                  echo "Hello from self-hosted runner!"
                  echo "Testing basic commands..."
                  node --version || echo "Node not installed" # checks if node is installed

            - name: Create test artifact
              run: |
                  echo "Test passed!" > test-result.txt # creates a file saying test passed

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: test-result.txt
